import type { TexlyreConfig } from '@/types/texlyre';

const config: TexlyreConfig = {
  title: 'TeXlyre',
  tagline: 'A local-first LaTeX & Typst collaborative web editor',
  url: 'https://REPLACE_WITH_SPACE_SUBDOMAIN.hf.space',
  baseUrl: '/texlyre/',
  organizationName: 'texlyre',
  projectName: 'texlyre',
  favicon: '/favicon.ico',
  airgap: {
    allowedDomains: [
      'hf.space',
      'texlyre.org',
      'texlyre.github.io',
      'typst.org',
    ],
    allowedProtocols: [
      'https:',
      'http:',
      'wss:',
      'ws:',
    ],
  },
  pwa: {
    enabled: true,
    themeColor: '#ffffff',
    manifest: './manifest.json',
    startUrl: './',
    backgroundColor: '#ffffff',
    icons: [
      {
        src: './assets/images/TeXlyre_notext_192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any maskable',
      },
    ],
    display: 'standalone',
  },
  plugins: {
    collaborative_viewers: ['bibtex', 'drawio', 'milkdown'],
    viewers: ['bibtex', 'image', 'media', 'pdf', 'drawio', 'milkdown'],
    renderers: ['pdf', 'canvas'],
    loggers: ['latex_visualizer', 'typst_visualizer'],
    bibliography: ['zotero', 'openalex'],
    lsp: [],
    backup: ['github', 'gitlab', 'forgejo', 'gitea'],
    themes: ['texlyre_slim', 'texlyre_wide', 'texlyre_mobile'],
  },
  userdata: {
    version: '1.2.1',
    default: {
      settings: {
        bibtexViewerAutoTidy: false,
        bibtexViewerTidyOptions: 'standard',
        canvasRendererAnnotations: true,
        canvasRendererEnable: true,
        canvasRendererInitialZoom: '100',
        canvasRendererTextSelection: true,
        collabAutoReconnect: false,
        collabAwarenessTimeout: 30,
        collabProviderType: 'webrtc',
        collabSignalingServers: 'wss://REPLACE_WITH_SPACE_SUBDOMAIN.hf.space/ywebrtc/',
        editorAutoSaveDelay: 1000,
        editorAutoSaveEnable: true,
        editorFontFamily: 'monospace',
        editorFontSize: 'lg',
        editorShowLineNumbers: true,
        editorSpellCheck: false,
        editorSyntaxHighlighting: true,
        editorThemeHighlights: 'auto',
        fileSyncAutoInterval: 10,
        fileSyncConflictResolution: 'prefer-latest',
        fileSyncEnable: true,
        fileSyncHoldTimeout: 30,
        fileSyncNotifications: true,
        fileSyncRequestTimeout: 60,
        fileSyncServerUrl: 'https://REPLACE_WITH_SPACE_SUBDOMAIN.hf.space/filepizza',
        fileSystemBackupAutoBackup: false,
        fileSystemBackupEnable: false,
        fileTreeFilesystemDragDrop: true,
        fileTreeInternalDragDrop: true,
        imageViewerAutoCenter: true,
        imageViewerEnableFilters: true,
        imageViewerQuality: 'high',
        latexEngine: 'pdftex',
        latexDefaultFormat: 'pdf',
        latexStoreCache: true,
        latexStoreWorkingDirectory: false,
        latexTexliveEndpoint: 'https://REPLACE_WITH_SPACE_SUBDOMAIN.hf.space/api/texlive',
        pdfRendererAnnotations: true,
        pdfRendererEnable: true,
        pdfRendererInitialZoom: '100',
        pdfRendererTextSelection: true,
        pdfViewerAutoScale: true,
        pdfViewerRenderingQuality: 'high',
        repositoryProxyUrl: 'https://proxy.texlyre.org/?url=',
        latexSourcemapEnabled: true,
        templatesApiUrl: 'https://texlyre.github.io/texlyre-templates/api/templates.json',
        themePlugin: 'texlyre-wide-theme',
        themeVariant: 'atom_light',
        typstAutoCompileOnOpen: false,
        typstDefaultFormat: 'canvas',
        typstSourcemapEnabled: true,
      },
      properties: {
        global: {
          latexOutputCollapsed: true,
          latexOutputWidth: 700,
          logVisualizerHeight: 600,
          logVisualizerCollapsed: false,
          pdfRendererZoom: 1,
          pdfRendererScrollView: true,
          canvasRendererZoom: 1,
          canvasRendererScrollView: true,
          sidebarCollapsed: false,
          sidebarWidth: 502,
          sourcemapShowFloatingButtons: true,
          toolbarVisible: true,
        },
      },
      secrets: {},
      records: {},
    },
    mobile: {
      settings: {
        themePlugin: 'texlyre-mobile-theme',
        imageViewerAutoCenter: true,
      },
      properties: {
        global: {
          projectListViewMode: 'list',
        },
      },
    },
    local: {
      settings: {
        collabSignalingServers: 'ws://localhost:7860/ywebrtc/',
        fileSyncServerUrl: 'http://localhost:7860/filepizza',
        latexTexliveEndpoint: 'http://localhost:7860/api/texlive',
        themeVariant: 'dark',
      },
      properties: {
        global: {
          pdfRendererScrollView: false,
        },
      },
    },
  },
};

export default config;
